/**
 * Dynamic robots.txt generated by Next.js App Router.
 * Served at /robots.txt on the live server.
 * Explicitly allows all major AI/LLM crawlers for GEO (Generative Engine Optimization).
 */
import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/_next/", "/404", "/500"],
      },
      // AI / LLM crawlers — explicitly allowed for GEO
      { userAgent: "GPTBot", allow: "/" },
      { userAgent: "ChatGPT-User", allow: "/" },
      { userAgent: "Google-Extended", allow: "/" },
      { userAgent: "anthropic-ai", allow: "/" },
      { userAgent: "PerplexityBot", allow: "/" },
      { userAgent: "YouBot", allow: "/" },
      { userAgent: "Bytespider", allow: "/" },
      { userAgent: "ClaudeBot", allow: "/" },
      { userAgent: "Applebot-Extended", allow: "/" },
    ],
    sitemap: [
      "https://www.drsaisekharphysician.com/sitemap.xml",
    ],
    host: "https://www.drsaisekharphysician.com",
  };
}
