/**
 * Dynamic sitemap generated by Next.js App Router.
 * This auto-generates alongside /public/sitemap.xml for search engines that
 * prefer the dynamic route. Both are referenced in robots.txt.
 */
import type { MetadataRoute } from "next";

const BASE_URL = "https://www.drsaisekharphysician.com";
const NOW = new Date().toISOString();

// All known service slugs
const SERVICE_SLUGS = [
  // High priority
  { slug: "type-ii-dm", priority: 0.85 },
  { slug: "hypertension-htn", priority: 0.85 },
  { slug: "hypothyroidism", priority: 0.8 },
  { slug: "dengue-fever", priority: 0.8 },
  { slug: "asthma", priority: 0.8 },
  { slug: "adult-vaccination", priority: 0.75 },
  { slug: "routine-health-checkups", priority: 0.75 },
  { slug: "migraine", priority: 0.75 },
  { slug: "rheumatoid-arthritis", priority: 0.75 },
  { slug: "dyslipidemia", priority: 0.7 },
  // Medium priority
  { slug: "type-1-dm", priority: 0.8 },
  { slug: "diabetic-neuropathy", priority: 0.75 },
  { slug: "diabetic-nephropathy", priority: 0.75 },
  { slug: "hyperthyroidism", priority: 0.75 },
  { slug: "ischemic-heart-disease", priority: 0.75 },
  { slug: "heart-failure", priority: 0.75 },
  { slug: "copd-chronic-obstructive-pulmonary-disease", priority: 0.75 },
  { slug: "pneumonia", priority: 0.75 },
  { slug: "malaria", priority: 0.75 },
  { slug: "viral-bacterial-infection", priority: 0.75 },
  { slug: "urinary-tract-infection-uti", priority: 0.75 },
  { slug: "acute-renal-failure", priority: 0.75 },
  { slug: "chronic-renal-failure", priority: 0.75 },
  { slug: "kidney-stones", priority: 0.75 },
  { slug: "jaundice-liver-problems", priority: 0.7 },
  { slug: "acute-gastritis", priority: 0.7 },
  { slug: "acute-gastroenteritis", priority: 0.7 },
  { slug: "acute-and-chronic-diarrhea", priority: 0.7 },
  { slug: "tension-headache", priority: 0.7 },
  { slug: "cervical-spondylosis", priority: 0.7 },
  { slug: "lumbar-spondylosis", priority: 0.7 },
  { slug: "septic-syndrome", priority: 0.7 },
  { slug: "geriatric-care", priority: 0.7 },
  // Lower priority
  { slug: "constipation", priority: 0.65 },
  { slug: "allergies", priority: 0.65 },
  { slug: "insomnia", priority: 0.65 },
  { slug: "connective-tissue-diseases", priority: 0.65 },
  { slug: "vitamin-deficiency", priority: 0.65 },
  { slug: "diet-lifestyle-modifications", priority: 0.65 },
  { slug: "substance-abuse", priority: 0.6 },
  { slug: "osteoarthritis", priority: 0.6 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const corePages: MetadataRoute.Sitemap = [
    {
      url: BASE_URL,
      lastModified: NOW,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/about-doctor`,
      lastModified: NOW,
      changeFrequency: "monthly",
      priority: 0.95,
    },
    {
      url: `${BASE_URL}/contact`,
      lastModified: NOW,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/services`,
      lastModified: NOW,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/about-clinic`,
      lastModified: NOW,
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/about-us`,
      lastModified: NOW,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/privacy-policy`,
      lastModified: NOW,
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];

  const servicePages: MetadataRoute.Sitemap = SERVICE_SLUGS.map(({ slug, priority }) => ({
    url: `${BASE_URL}/services/${slug}`,
    lastModified: NOW,
    changeFrequency: "monthly" as const,
    priority,
  }));

  return [...corePages, ...servicePages];
}
